language: node_js
node_js:
- node
cache:
- npm
script:
- npm run test
- npm run lint
- npm run build
before_deploy:
- cp CNAME public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAGES_DEPLOY_TOKEN
  keep-history: true
  repo: Ricool06/ricool06.github.io
  target-branch: master
  local-dir: public
  on:
    branch: master